/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Joseph' at '2/1/16 9:45 PM' with Gradle 2.6
 *
 * @author Joseph, @date 2/1/16 9:45 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
